# Generated by Django 4.0.5 on 2022-06-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_categoria_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='foto',
        ),
    ]
